@ -1,20 +1,28 @@
---
title: "My website and data analysis portfolio - Sri Lakshmi"
title: ""
output: 
  html_document:
    css: styles.css
---
<div class="header" align="left">
  <h1>Welcome to My Website 
  
   Sri Lakshmi  - DA Portfolio </h1> 
</div>

# Hello

### And hello again
# Introduction

Welcome to **my website** and _data analysis portfolio._ 
Hi, I am **Sri Lakshmi Sudha Ganni**, currently pursuing my Master’s in Data Analytics from UTSA. My background is in chemical engineering with industry experience focused on chemical testing of water and wastewater. I am passionate about data analysis and looking forward to working in the field of data analytics. Throughout my journey, I have gained proficiency in **R, Python, SQL**, and **SAS**. I have explored machine learning techniques such as support vector machines, natural language processing, clustering, and regression, and have worked on data visualization using **ggplot2** and **matplotlib**.

# Data Analytics Experience

I have worked on projects analyzing resources available for cancer patients and am currently focused on predicting the housing market prices in San Antonio. I am eager to work on more projects to enhance my experience in data analytics, especially those focusing on data visualization and machine learning.

* Please use the `Menu Bar` above to look around.
* Have fun!
# Research Interest

**Feel free to change this text any way you want 😁!**
My primary area of interest lies at the intersection of data analytics and chemical of engineering. Specifically, I am keen on applying machine learning techniques to analyze and discover underlying trends in chemical plant data and material testing.

My name is Sri. I have Bachelor's in Chemical Engineering.
# Hobbies

I love playing Racquetball, trekking and passionate about Photography.
In my free time, I love playing Racquetball, trekking, and am passionate about photography.