<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Sri Lakshmi - DA Portfolio - Exploratory Data Analysis of NCHS Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Sri Lakshmi - DA Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../aboutme.html" rel="" target="">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="../starter-analysis-exercise/products/report/starter-analysis-report.html" rel="" target="">
 <span class="dropdown-text">Starter Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../coding-exercise/coding-exercise.html" rel="" target="">
 <span class="dropdown-text">R Coding Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentation-exercise/presentation-exercise.html" rel="" target="">
 <span class="dropdown-text">Presentation Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tidytuesday-exercise/tidytuesday-exercise.html" rel="" target="">
 <span class="dropdown-text">Tidy Tuesday Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-exercise/data-exercise.html" rel="" target="">
 <span class="dropdown-text">Data Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../cdcdata-exercise/cdcdata-exercise.html" rel="" target="">
 <span class="dropdown-text">Data Analysis Exercise</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/sls-chundru/sriganni-P2-portfolio" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exploratory Data Analysis of NCHS Data</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="r-coding-exercise-custom-special-style">

<p><strong>Brief Decription of the Data</strong>:</p>
<p><strong>Title:</strong> NCHS - Death rates and life expectancy at birth</p>
<p><strong>Description:</strong> we will explore a dataset from the National Center for Health Statistics (NCHS) that contains information about death rates and life expectancy at birth. Our goal is to clean the data, perform exploratory data analysis (EDA), and summarize the variables by their distributions.</p>
<p>This dataset of U.S. mortality trends since 1900 highlights the differences in age-adjusted death rates and life expectancy at birth by race and sex.</p>
<p>Age-adjusted death rates (deaths per 100,000) after 1998 are calculated based on the 2000 U.S. standard population. Populations used for computing death rates for 2011–2017 are postcensal estimates based on the 2010 census, estimated as of July 1, 2010. Rates for census years are based on populations enumerated in the corresponding censuses. Rates for noncensus years between 2000 and 2010 are revised using updated intercensal population estimates and may differ from rates previously published. Data on age-adjusted death rates prior to 1999 are taken from historical data (see References below).</p>
<p>Life expectancy data are available up to 2017. Due to changes in categories of race used in publications, data are not available for the black population consistently before 1968, and not at all before 1960. More information on historical data on age-adjusted death rates is available at https://www.cdc.gov/nchs/nvss/mortality/hist293.htm.</p>
<p><strong>Sources:</strong> CDC/NCHS, National Vital Statistics System, historical data, 1900-1998 (see https://www.cdc.gov/nchs/nvss/mortality_historical_data.htm); CDC/NCHS, National Vital Statistics System, mortality data (see http://www.cdc.gov/nchs/deaths.htm); and CDC WONDER (see http://wonder.cdc.gov).</p>
<section id="load-necessary-libraries" class="level1">
<h1>Load necessary libraries:</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at /Users/srilakshmi/Documents/GitHub/sriganni-P2-portfolio</code></pre>
</div>
</div>
</section>
<section id="read-the-data" class="level1">
<h1>Read the data:</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the data</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>file_path <span class="ot">&lt;-</span> <span class="fu">here</span>(<span class="st">"cdcdata-exercise"</span>,<span class="st">"NCHS_-_Death_rates_and_life_expectancy_at_birth_20240701.csv"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(file_path)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1071 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Race, Sex
dbl (3): Year, Average Life Expectancy (Years), Age-adjusted Death Rate

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</section>
<section id="display-the-first-few-rows-of-the-dataset" class="level1">
<h1>Display the first few rows of the dataset:</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
   Year Race      Sex        Average Life Expectancy (Y…¹ Age-adjusted Death R…²
  &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;                             &lt;dbl&gt;                  &lt;dbl&gt;
1  1900 All Races Both Sexes                         47.3                  2518 
2  1901 All Races Both Sexes                         49.1                  2473.
3  1902 All Races Both Sexes                         51.5                  2301.
4  1903 All Races Both Sexes                         50.5                  2379 
5  1904 All Races Both Sexes                         47.6                  2502.
6  1905 All Races Both Sexes                         48.7                  2424.
# ℹ abbreviated names: ¹​`Average Life Expectancy (Years)`,
#   ²​`Age-adjusted Death Rate`</code></pre>
</div>
</div>
</section>
<section id="check-the-structure-of-the-dataset" class="level1">
<h1>Check the structure of the dataset:</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [1,071 × 5] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Year                           : num [1:1071] 1900 1901 1902 1903 1904 ...
 $ Race                           : chr [1:1071] "All Races" "All Races" "All Races" "All Races" ...
 $ Sex                            : chr [1:1071] "Both Sexes" "Both Sexes" "Both Sexes" "Both Sexes" ...
 $ Average Life Expectancy (Years): num [1:1071] 47.3 49.1 51.5 50.5 47.6 48.7 48.7 47.6 51.1 52.1 ...
 $ Age-adjusted Death Rate        : num [1:1071] 2518 2473 2301 2379 2502 ...
 - attr(*, "spec")=
  .. cols(
  ..   Year = col_double(),
  ..   Race = col_character(),
  ..   Sex = col_character(),
  ..   `Average Life Expectancy (Years)` = col_double(),
  ..   `Age-adjusted Death Rate` = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
</section>
<section id="clean-the-data" class="level1">
<h1>Clean the data:</h1>
</section>
<section id="remove-any-rows-with-na-values" class="level1">
<h1>Remove any rows with NA values:</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter_all</span>(<span class="fu">any_vars</span>(<span class="sc">!</span><span class="fu">is.na</span>(.)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="replace-missing-values-coded-as-999-with-na" class="level1">
<h1>Replace missing values coded as 999 with NA:</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.numeric, <span class="sc">~</span><span class="fu">na_if</span>(., <span class="dv">999</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="select-a-few-variables-for-analysis-adjust-based-on-actual-variable-names-in-the-dataset" class="level1">
<h1>Select a few variables for analysis (adjust based on actual variable names in the dataset):</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>selected_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Year, Sex, Race, <span class="st">"Average Life Expectancy (Years)"</span>, <span class="st">"Age-adjusted Death Rate"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exploratory-data-analysis-eda" class="level1">
<h1>Exploratory Data Analysis (EDA):</h1>
</section>
<section id="summary-statistics" class="level1">
<h1>Summary statistics:</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(selected_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Year          Sex                Race          
 Min.   :1900   Length:1071        Length:1071       
 1st Qu.:1929   Class :character   Class :character  
 Median :1959   Mode  :character   Mode  :character  
 Mean   :1959                                        
 3rd Qu.:1989                                        
 Max.   :2018                                        
                                                     
 Average Life Expectancy (Years) Age-adjusted Death Rate
 Min.   :29.1                    Min.   : 611.3         
 1st Qu.:57.1                    1st Qu.:1013.0         
 Median :66.8                    Median :1513.7         
 Mean   :64.5                    Mean   :1593.1         
 3rd Qu.:73.9                    3rd Qu.:2057.2         
 Max.   :81.4                    Max.   :3845.7         
 NA's   :6                                              </code></pre>
</div>
</div>
<section id="summary-of-categorical-variables" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-categorical-variables">Summary of categorical variables:</h2>
<p>We’ll start by summarizing the categorical variables (Sex and Race) by showing the percentage of each category.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>cat_summary_sex <span class="ot">&lt;-</span> selected_data <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Sex) <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percentage =</span> count <span class="sc">/</span> <span class="fu">sum</span>(count) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>cat_summary_race <span class="ot">&lt;-</span> selected_data <span class="sc">%&gt;%</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Race) <span class="sc">%&gt;%</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percentage =</span> count <span class="sc">/</span> <span class="fu">sum</span>(count) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cat_summary_sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  Sex        count percentage
  &lt;chr&gt;      &lt;int&gt;      &lt;dbl&gt;
1 Both Sexes   357       33.3
2 Female       357       33.3
3 Male         357       33.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cat_summary_race)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  Race      count percentage
  &lt;chr&gt;     &lt;int&gt;      &lt;dbl&gt;
1 All Races   357       33.3
2 Black       357       33.3
3 White       357       33.3</code></pre>
</div>
</div>
<p>Sex Distribution: The dataset is evenly distributed across the sex categories: Both Sexes, Female, and Male. Each category represents 33.33% of the total dataset with 357 entries each. This balanced representation ensures an unbiased analysis across sexes.</p>
<p>Race Distribution: The dataset is equally divided among the race categories: All Races, Black, and White, with each category comprising 33.33% of the total dataset (357 entries each). This equal distribution ensures comprehensive analysis across races.</p>
</section>
</section>
<section id="distribution-of-categorical-variables" class="level1">
<h1>Distribution of categorical variables:</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>cat_summary <span class="ot">&lt;-</span> selected_data <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Sex, Race) <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">'drop'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percentage =</span> count <span class="sc">/</span> <span class="fu">sum</span>(count) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>cat_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 4
  Sex        Race      count percentage
  &lt;chr&gt;      &lt;chr&gt;     &lt;int&gt;      &lt;dbl&gt;
1 Both Sexes All Races   119       11.1
2 Both Sexes Black       119       11.1
3 Both Sexes White       119       11.1
4 Female     All Races   119       11.1
5 Female     Black       119       11.1
6 Female     White       119       11.1
7 Male       All Races   119       11.1
8 Male       Black       119       11.1
9 Male       White       119       11.1</code></pre>
</div>
</div>
</section>
<section id="continuous-variables" class="level1">
<h1>Continuous Variables:</h1>
<p>Next, we’ll summarize the continuous variables (Age-adjusted Death Rate and Average Life Expectancy (Years)) by plotting their distributions and calculating their mean and standard deviation.</p>
</section>
<section id="plot-distribution-of-age-adjusted-death-rate" class="level1">
<h1>Plot distribution of age-adjusted death rate:</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(selected_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Age-adjusted Death Rate</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">50</span>, <span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Age-adjusted Death Rates"</span>, <span class="at">x =</span> <span class="st">"Age-adjusted Death Rate"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The histogram shows age-adjusted death rates ranging from 0 to 4000, with the highest frequencies. The frequency decreases as the death rate increases, indicating fewer occurrences at higher death rates.This visualization helps identify the concentration and spread of death rates within the population, highlighting areas with the most common and least common death rates.</p>
</section>
<section id="summary-statistics-for-age-adjusted-death-rate" class="level1">
<h1>Summary statistics for age-adjusted death rate:</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>death_rate_summary <span class="ot">&lt;-</span> selected_data <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Age-adjusted Death Rate</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(<span class="st">`</span><span class="at">Age-adjusted Death Rate</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(death_rate_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
   mean    sd
  &lt;dbl&gt; &lt;dbl&gt;
1 1593.  682.</code></pre>
</div>
</div>
<p>The summary statistics table provides the mean and standard deviation for the age-adjusted death rates. The mean age-adjusted death rate is approximately 1593.06, with a standard deviation of 682.37. This indicates that the average death rate is around 1593 deaths per 100,000 population, with considerable variability across the dataset.</p>
</section>
<section id="plot-distribution-of-average-life-expectancyyears" class="level1">
<h1>Plot distribution of Average life expectancy(Years):</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(selected_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Average Life Expectancy (Years)</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">fill =</span> <span class="st">"green"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Life Expectancy"</span>, <span class="at">x =</span> <span class="st">"Life Expectancy (Years)"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 6 rows containing non-finite values (`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The histogram illustrates the distribution of average life expectancy in the dataset, ranging from approximately 30 to 85 years. The frequency peaks around 70 years, indicating a higher number of occurrences in this range. This visualization helps identify the spread and concentration of life expectancy across the population, highlighting areas with the highest and lowest frequencies.</p>
</section>
<section id="summary-statistics-for-average-life-expectancy" class="level1">
<h1>Summary statistics for Average life expectancy:</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>life_expectancy_summary <span class="ot">&lt;-</span> selected_data <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Average Life Expectancy (Years)</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(<span class="st">`</span><span class="at">Average Life Expectancy (Years)</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(life_expectancy_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
   mean    sd
  &lt;dbl&gt; &lt;dbl&gt;
1  64.5  11.8</code></pre>
</div>
</div>
<p>The summary statistics table for average life expectancy shows a mean of 64.50 years and a standard deviation of 11.84 years. This indicates that the average life expectancy in the dataset is approximately 64.5 years, with a variability of about 11.8 years across the data points.</p>
</section>
<section id="boxplots" class="level1">
<h1>Boxplots:</h1>
<p>We’ll also create boxplots to visualize the distribution of Age-adjusted Death Rate by Sex and Average Life Expectancy (Years) by Race.</p>
</section>
<section id="boxplot-of-age-adjusted-death-rate-by-sex" class="level1">
<h1>Boxplot of age-adjusted death rate by sex:</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(selected_data, <span class="fu">aes</span>(<span class="at">x =</span> Sex, <span class="at">y =</span> <span class="st">`</span><span class="at">Age-adjusted Death Rate</span><span class="st">`</span>, <span class="at">fill =</span> Sex)) <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Boxplot of Age-adjusted Death Rate by Sex"</span>, <span class="at">x =</span> <span class="st">"Sex"</span>, <span class="at">y =</span> <span class="st">"Age-adjusted Death Rate"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The boxplot shows the distribution of age-adjusted death rates across different sex categories: Both Sexes, Female, and Male.</p>
<p>1.The median death rate for Both Sexes and Females is lower compared to Males.</p>
<p>2.The interquartile range (IQR) is similar for Both Sexes and Females but slightly larger for Males, indicating more variability in the male category.</p>
<p>3.There are several outliers in the Male category, suggesting that there are some instances of unusually high death rates.</p>
<p>This visualization highlights the differences in death rates among the sex categories, with males showing higher median and more variability in death rates.</p>
</section>
<section id="boxplot-of-life-expectancy-by-race" class="level1">
<h1>Boxplot of life expectancy by race:</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(selected_data, <span class="fu">aes</span>(<span class="at">x =</span> Race, <span class="at">y =</span> <span class="st">`</span><span class="at">Average Life Expectancy (Years)</span><span class="st">`</span>, <span class="at">fill =</span> Race)) <span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Boxplot of Average Life Expectancy by Race"</span>, <span class="at">x =</span> <span class="st">"Race"</span>, <span class="at">y =</span> <span class="st">"Average Life Expectancy (Years)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 6 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The boxplot compares average life expectancy across race categories: All Races, Black, and White.</p>
<p>1.The median life expectancy is similar for All Races and White categories, slightly lower for Black.</p>
<p>2.The interquartile range is largest for the White category, indicating more variability.</p>
<p>3.The Black category shows the lowest median.</p>
<p>This visualization highlights the differences in life expectancy across races, with the White category exhibiting the highest variability.</p>
</section>
<section id="this-section-contributed-by-seth-harris." class="level1">
<h1><strong>This section contributed by Seth Harris.</strong></h1>
<section id="load-necessary-libraries-1" class="level3">
<h3 class="anchored" data-anchor-id="load-necessary-libraries-1">Load necessary libraries:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(synthpop)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Find out more at https://www.synthpop.org.uk/</code></pre>
</div>
</div>
</section>
<section id="generate-synthetic-data" class="level3">
<h3 class="anchored" data-anchor-id="generate-synthetic-data">Generate synthetic data:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Sri's cleaned and processed data</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>file_path <span class="ot">&lt;-</span> <span class="fu">here</span>(<span class="st">"cdcdata-exercise"</span>, <span class="st">"NCHS_-_Death_rates_and_life_expectancy_at_birth_20240701.csv"</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>original_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(file_path)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1071 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Race, Sex
dbl (3): Year, Average Life Expectancy (Years), Age-adjusted Death Rate

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename columns to remove spaces</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>original_data <span class="ot">&lt;-</span> original_data <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Average_Life_Expectancy_Years =</span> <span class="st">`</span><span class="at">Average Life Expectancy (Years)</span><span class="st">`</span>,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">Age_adjusted_Death_Rate =</span> <span class="st">`</span><span class="at">Age-adjusted Death Rate</span><span class="st">`</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate synthetic data using synthpop</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>synthetic_data <span class="ot">&lt;-</span> <span class="fu">syn</span>(original_data)<span class="sc">$</span>syn</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Variable(s): Race, Sex have been changed for synthesis from character to factor.

Synthesis
-----------
 Year Race Sex Average_Life_Expectancy_Years Age_adjusted_Death_Rate</code></pre>
</div>
</div>
</section>
<section id="display-the-first-few-rows-of-the-synthetic-dataset" class="level3">
<h3 class="anchored" data-anchor-id="display-the-first-few-rows-of-the-synthetic-dataset">Display the first few rows of the synthetic dataset:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(synthetic_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Year      Race        Sex Average_Life_Expectancy_Years
1 1900     White Both Sexes                          49.1
2 1939     Black Both Sexes                          51.7
3 2011     Black Both Sexes                          75.5
4 1951 All Races     Female                          71.1
5 1991     White     Female                          78.8
6 1997     Black Both Sexes                          71.8
  Age_adjusted_Death_Rate
1                  2447.9
2                  2384.3
3                   849.3
4                  1271.8
5                   737.9
6                  1135.7</code></pre>
</div>
</div>
</section>
<section id="check-the-structure-of-the-synthetic-dataset" class="level3">
<h3 class="anchored" data-anchor-id="check-the-structure-of-the-synthetic-dataset">Check the structure of the synthetic dataset:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(synthetic_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   1071 obs. of  5 variables:
 $ Year                         : num  1900 1939 2011 1951 1991 ...
 $ Race                         : chr  "White" "Black" "Black" "All Races" ...
 $ Sex                          : chr  "Both Sexes" "Both Sexes" "Both Sexes" "Female" ...
 $ Average_Life_Expectancy_Years: num  49.1 51.7 75.5 71.1 78.8 71.8 81.3 77.7 66.8 47.3 ...
 $ Age_adjusted_Death_Rate      : num  2448 2384 849 1272 738 ...</code></pre>
</div>
</div>
</section>
</section>
<section id="exploratory-data-analysis-eda-on-synthetic-data" class="level1">
<h1>Exploratory Data Analysis (EDA) on Synthetic Data</h1>
<p><strong>In this section, I will perform some exploratory/descriptive analysis on the synthetic dataset, similar to Sri’s analysis.</strong></p>
<section id="summary-statistics-1" class="level2">
<h2 class="anchored" data-anchor-id="summary-statistics-1"><strong>Summary statistics:</strong></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(synthetic_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Year          Race               Sex           
 Min.   :1900   Length:1071        Length:1071       
 1st Qu.:1930   Class :character   Class :character  
 Median :1959   Mode  :character   Mode  :character  
 Mean   :1959                                        
 3rd Qu.:1988                                        
 Max.   :2018                                        
                                                     
 Average_Life_Expectancy_Years Age_adjusted_Death_Rate
 Min.   :29.10                 Min.   : 611.3         
 1st Qu.:58.30                 1st Qu.: 991.1         
 Median :66.80                 Median :1532.0         
 Mean   :64.64                 Mean   :1587.4         
 3rd Qu.:73.90                 3rd Qu.:2005.6         
 Max.   :81.40                 Max.   :3654.7         
 NA's   :4                                            </code></pre>
</div>
</div>
</section>
<section id="summary-of-categorical-variables-1" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-categorical-variables-1">Summary of categorical variables:</h2>
<p>I will summarize the categorical variables (e.g., <code>Sex</code> and <code>Race</code>) by showing the percentage of each category.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>cat_summary_sex <span class="ot">&lt;-</span> synthetic_data <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Sex) <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percentage =</span> count <span class="sc">/</span> <span class="fu">sum</span>(count) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>cat_summary_race <span class="ot">&lt;-</span> synthetic_data <span class="sc">%&gt;%</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Race) <span class="sc">%&gt;%</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percentage =</span> count <span class="sc">/</span> <span class="fu">sum</span>(count) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cat_summary_sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  Sex        count percentage
  &lt;chr&gt;      &lt;int&gt;      &lt;dbl&gt;
1 Both Sexes   349       32.6
2 Female       363       33.9
3 Male         359       33.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cat_summary_race)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  Race      count percentage
  &lt;chr&gt;     &lt;int&gt;      &lt;dbl&gt;
1 All Races   349       32.6
2 Black       357       33.3
3 White       365       34.1</code></pre>
</div>
</div>
</section>
<section id="distribution-of-categorical-variables-1" class="level2">
<h2 class="anchored" data-anchor-id="distribution-of-categorical-variables-1">Distribution of categorical variables:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>cat_summary <span class="ot">&lt;-</span> synthetic_data <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Sex, Race) <span class="sc">%&gt;%</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">'drop'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percentage =</span> count <span class="sc">/</span> <span class="fu">sum</span>(count) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>cat_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 4
  Sex        Race      count percentage
  &lt;chr&gt;      &lt;chr&gt;     &lt;int&gt;      &lt;dbl&gt;
1 Both Sexes All Races   117      10.9 
2 Both Sexes Black        94       8.78
3 Both Sexes White       138      12.9 
4 Female     All Races   125      11.7 
5 Female     Black       138      12.9 
6 Female     White       100       9.34
7 Male       All Races   107       9.99
8 Male       Black       125      11.7 
9 Male       White       127      11.9 </code></pre>
</div>
</div>
</section>
<section id="continuous-variables-1" class="level2">
<h2 class="anchored" data-anchor-id="continuous-variables-1">Continuous Variables:</h2>
<p>Next, I will summarize the continuous variables (Age_adjusted_Death_Rate and Average_Life_Expectancy_Years) by plotting their distributions and calculating their mean and standard deviation.</p>
</section>
<section id="plot-distribution-of-age_adjusted_death_rate" class="level2">
<h2 class="anchored" data-anchor-id="plot-distribution-of-age_adjusted_death_rate">Plot distribution of Age_adjusted_Death_Rate:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(synthetic_data, <span class="fu">aes</span>(<span class="at">x =</span> Age_adjusted_Death_Rate)) <span class="sc">+</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">50</span>, <span class="at">fill =</span> <span class="st">"red"</span>, <span class="at">color =</span> <span class="st">"orange"</span>) <span class="sc">+</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Age-adjusted Death Rates (Synthetic Data)"</span>, <span class="at">x =</span> <span class="st">"Age-adjusted Death Rate"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="distribution-of-age-adjusted-death-rates-synthetic-data" class="level3">
<h3 class="anchored" data-anchor-id="distribution-of-age-adjusted-death-rates-synthetic-data">Distribution of Age-adjusted Death Rates (Synthetic Data)</h3>
<section id="description" class="level4">
<h4 class="anchored" data-anchor-id="description">Description:</h4>
<p>This histogram shows the distribution of age-adjusted death rates in the synthetic dataset. The x-axis represents the age-adjusted death rates, while the y-axis shows the frequency of these rates.</p>
</section>
<section id="findings" class="level4">
<h4 class="anchored" data-anchor-id="findings">Findings:</h4>
<ul>
<li><p>The histogram displays a right-skewed distribution, with a peak around the lower values of death rates.</p></li>
<li><p>Most of the synthetic data points have death rates concentrated between 500 to 1500, with decreasing frequency as the death rates increase.</p></li>
<li><p>The synthetic data mirrors the distribution characteristics observed in the original dataset, maintaining a similar skewness and concentration of values.</p></li>
</ul>
</section>
</section>
</section>
<section id="summary-statistics-for-age_adjusted_death_rate" class="level2">
<h2 class="anchored" data-anchor-id="summary-statistics-for-age_adjusted_death_rate">Summary statistics for <code>Age_adjusted_Death_Rate</code>:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>death_rate_summary <span class="ot">&lt;-</span> synthetic_data <span class="sc">%&gt;%</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(Age_adjusted_Death_Rate, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(Age_adjusted_Death_Rate, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(death_rate_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     mean       sd
1 1587.39 676.0813</code></pre>
</div>
</div>
</section>
<section id="plot-distribution-of-average_life_expectancy_years" class="level2">
<h2 class="anchored" data-anchor-id="plot-distribution-of-average_life_expectancy_years">Plot distribution of <code>Average_Life_Expectancy_Years</code>:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(synthetic_data, <span class="fu">aes</span>(<span class="at">x =</span> Average_Life_Expectancy_Years)) <span class="sc">+</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">color =</span> <span class="st">"lightblue"</span>) <span class="sc">+</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Average Life Expectancy (Years) (Synthetic Data)"</span>, <span class="at">x =</span> <span class="st">"Average Life Expectancy (Years)"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 4 rows containing non-finite values (`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="distribution-of-average-life-expectancy-years-synthetic-data" class="level3">
<h3 class="anchored" data-anchor-id="distribution-of-average-life-expectancy-years-synthetic-data">Distribution of Average Life Expectancy (Years) (Synthetic Data)</h3>
<section id="description-1" class="level4">
<h4 class="anchored" data-anchor-id="description-1">Description:</h4>
<p>This histogram illustrates the distribution of average life expectancy in the synthetic dataset. The x-axis represents the average life expectancy in years, and the y-axis shows the frequency of these values.</p>
</section>
<section id="findings-1" class="level4">
<h4 class="anchored" data-anchor-id="findings-1">Findings:</h4>
<ul>
<li><p>The histogram reveals a distribution with a peak around 70 years, indicating a higher frequency of data points in this range.</p></li>
<li><p>The distribution is somewhat bimodal, with another smaller peak around 60 years.</p></li>
<li><p>The synthetic data closely follows the distribution observed in the original dataset, with a similar concentration of values around 70 years and a similar spread of life expectancy values.</p></li>
</ul>
</section>
</section>
</section>
<section id="summary-statistics-for-average_life_expectancy_years" class="level2">
<h2 class="anchored" data-anchor-id="summary-statistics-for-average_life_expectancy_years">Summary statistics for <code>Average_Life_Expectancy_Years</code>:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>life_expectancy_summary <span class="ot">&lt;-</span> synthetic_data <span class="sc">%&gt;%</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(Average_Life_Expectancy_Years, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(Average_Life_Expectancy_Years, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(life_expectancy_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      mean       sd
1 64.64227 11.75375</code></pre>
</div>
</div>
</section>
<section id="boxplots-1" class="level2">
<h2 class="anchored" data-anchor-id="boxplots-1">Boxplots:</h2>
<p>I will also create boxplots to visualize the distribution of Age_adjusted_Death_Rate by Sex and Average_Life_Expectancy_Years by Race.</p>
</section>
<section id="boxplot-of-age_adjusted_death_rate-by-sex" class="level2">
<h2 class="anchored" data-anchor-id="boxplot-of-age_adjusted_death_rate-by-sex">Boxplot of <code>Age_adjusted_Death_Rate</code> by <code>Sex</code>:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(synthetic_data, <span class="fu">aes</span>(<span class="at">x =</span> Sex, <span class="at">y =</span> Age_adjusted_Death_Rate, <span class="at">fill =</span> Sex)) <span class="sc">+</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Boxplot of Age-adjusted Death Rate by Sex (Synthetic Data)"</span>, <span class="at">x =</span> <span class="st">"Sex"</span>, <span class="at">y =</span> <span class="st">"Age-adjusted Death Rate"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="boxplot-of-age-adjusted-death-rate-by-sex-synthetic-data" class="level3">
<h3 class="anchored" data-anchor-id="boxplot-of-age-adjusted-death-rate-by-sex-synthetic-data">Boxplot of Age-adjusted Death Rate by Sex (Synthetic Data)</h3>
<section id="description-2" class="level4">
<h4 class="anchored" data-anchor-id="description-2">Description:</h4>
<p>This boxplot compares the distribution of age-adjusted death rates across different sex categories in the synthetic dataset: Both Sexes, Female, and Male.</p>
</section>
<section id="findings-2" class="level4">
<h4 class="anchored" data-anchor-id="findings-2">Findings:</h4>
<ul>
<li><p>The median death rate for both sexes and females is lower compared to males, consistent with the original data.</p></li>
<li><p>The interquartile range (IQR) for males is slightly larger, indicating more variability in this category.</p></li>
<li><p>There are several outliers in the male category, suggesting instances of unusually high death rates, which is also consistent with the original data.</p></li>
<li><p>The boxplot confirms that the synthetic data maintains the same distribution characteristics and variability as observed in the original dataset.</p></li>
</ul>
</section>
</section>
</section>
<section id="boxplot-of-average_life_expectancy_years-by-race" class="level2">
<h2 class="anchored" data-anchor-id="boxplot-of-average_life_expectancy_years-by-race">Boxplot of <code>Average_Life_Expectancy_Years</code> by <code>Race</code>:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(synthetic_data, <span class="fu">aes</span>(<span class="at">x =</span> Race, <span class="at">y =</span> Average_Life_Expectancy_Years, <span class="at">fill =</span> Race)) <span class="sc">+</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Boxplot of Average Life Expectancy (Years) by Race (Synthetic Data)"</span>, <span class="at">x =</span> <span class="st">"Race"</span>, <span class="at">y =</span> <span class="st">"Average Life Expectancy (Years)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 4 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="boxplot-of-average-life-expectancy-years-by-race-synthetic-data" class="level3">
<h3 class="anchored" data-anchor-id="boxplot-of-average-life-expectancy-years-by-race-synthetic-data">Boxplot of Average Life Expectancy (Years) by Race (Synthetic Data)</h3>
<section id="description-3" class="level4">
<h4 class="anchored" data-anchor-id="description-3">Description:</h4>
<p>This boxplot visualizes the distribution of average life expectancy across race categories in the synthetic dataset: All Races, Black, and White.</p>
</section>
<section id="findings-3" class="level4">
<h4 class="anchored" data-anchor-id="findings-3">Findings:</h4>
<ul>
<li><p>The median life expectancy is similar for All Races and White categories, slightly lower for Black, consistent with the original data.</p></li>
<li><p>The interquartile range is largest for the White category, indicating more variability in this group.</p></li>
<li><p>The Black category shows the lowest median life expectancy.</p></li>
<li><p>The synthetic data successfully mimics the distribution characteristics of the original dataset, including the central tendencies and variability across race categories.</p></li>
</ul>
</section>
</section>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>In this analysis, I successfully generated synthetic data based on the original cleaned dataset provided by Sri. I then performed exploratory data analysis (EDA) on the synthetic data, producing summary statistics, histograms, and boxplots to compare with the original data. This approach helps ensure the synthetic data closely mimics the characteristics and distributions of the original data, enabling further analysis and modeling.</p>
</section>
<section id="comments-on-the-analysis" class="level1">
<h1>Comments on the Analysis</h1>
<ol type="1">
<li><p><strong>Data Cleaning</strong>: I started by loading Sri’s original data and renaming columns to avoid spaces, which synthpop requires for generating synthetic data correctly.</p></li>
<li><p><strong>Synthetic Data Generation</strong>: Using the <code>synthpop</code> package, I generated a synthetic dataset based on the original data. The synthetic data retains the structure and distribution of the original dataset.</p></li>
<li><p><strong>Exploratory Data Analysis (EDA)</strong>: I conducted a similar EDA on the synthetic data as Sri did on the original data, including summary statistics, histograms, and boxplots.</p></li>
<li><p><strong>Comparison</strong>: The EDA of the synthetic data closely mirrors the original data, demonstrating that the synthetic data maintains similar distributions and relationships among variables. This is crucial for ensuring that any analysis or modeling performed on the synthetic data would yield results similar to those obtained from the original data.</p></li>
</ol>
<p>By generating and analyzing synthetic data, I can share and analyze sensitive datasets without compromising privacy, ensuring that the synthetic data provides a reliable stand-in for the original dataset. This approach allows us to conduct meaningful analyses and derive insights while protecting the confidentiality of the original data.</p>


</section>

</div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>